#![allow(non_camel_case_types)]
#![allow(non_snake_case)]


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Area {
    END_M01AA,
    END_M01AB,

    TAR_M02AF,
    TAR_M02AA,
    TAR_M02AC,
    TAR_M02AE,
    TAR_M02AB,
    TAR_M02AD,
    TAR_M03AA,
    TAR_M03AD,
    TAR_M03AE,
    TAR_M03AB,
    TAR_M11AA,
    TAR_M11AB,
    TAR_M04AA,
    TAR_M05AA,
    TAR_M05AB,
    TAR_M10AA,
    TAR_M10AB,
    TAR_M10AC,
    TAR_M03AF,
    TAR_M03MG,
    TAR_M09AA,
    TAR_M09AB,
    TAR_M08AA,

    DANM13,
    DANM14AA,
    DANM14AB,
    DANM14AC,
    DANM14AD,
    DANM14AE,
    DANM16,
    DANM15,

    MANM26AD,
    MANM26AC,
    MANM26AA,
    MANM26AE,
    MANM26AB,
    MANM26MG,
    MANM27AA,
    MANM28AA,
    MANM28AB,
    MANM28AC,
    MANM28AD,

    KORR_M33AA,
    KORR_M33AB,
    KORR_M35AA,
    KORR_M36AA,
    KORR_M34AA,
    KORR_M38AA,
    KORR_M37AA,
    KORR_M38AB,
    KORR_M39AA,

    KAS_M22AA,
    KAS_M22AB,
    KAS_M23AA,
    KAS_M23AB,
    KAS_M23AC,
    KAS_M24AA,
    KAS_M25AA,
    KAS_M23AD,

    TAT_M17AB,
    TAT_M17AA,
    TAT_M17AD,
    TAT_M17AG,
    TAT_M17AE,
    TAT_M17MG,
    TAT_M17AF,
    TAT_M17AC,
    TAT_M18AA,
    TAT_M18AB,
    TAT_M20AA,
    TAT_M18AC,

    LEV_M40AA,
    LEV_M40AB,
    LEV_M40AD,
    LEV_M40AC,

    UNK_M41AA,
    UNK_M41AC,
    UNK_M43AA,
    UNK_M41AD,
    UNK_M41AB,
    UNK_M42AA,
    UNK_M44AA,
    UNK_M44AB,
    UNK_M44AC,

    STA_M45AA,
    STA_M45AB,
    STA_M45AC,
    STA_M45AD,

    EBO_M12AA,
    EBO_M41AA,
    EBO_M46AB,

    LIV_M99AA,
    STUNT_00,
    STUNT_03A,
    STUNT_06,
    STUNT_07,
    M12AB,
    STUNT_12,
    STUNT_14,
    STUNT_16,
    STUNT_19,
    EBO_M40AA,
    STUNT_31B,
    EBO_M40AD,
    STUNT_18,
    STUNT_35,
    STUNT_42,
    STUNT_44,
    STUNT_34,
    STUNT_50A,
    STUNT_54A,
    STUNT_55A,
    STUNT_56A,
    STUNT_57A,
    BastilaSaved,

    Unknown(String),
}

impl From<&str> for Area {
    fn from(s: &str) -> Self {
        let key = s.trim_matches(char::from(0)).to_uppercase();
        match key.as_str() {
            "END_M01AA" => Area::END_M01AA,
            "END_M01AB" => Area::END_M01AB,

            "TAR_M02AF" => Area::TAR_M02AF,
            "TAR_M02AA" => Area::TAR_M02AA,
            "TAR_M02AC" => Area::TAR_M02AC,
            "TAR_M02AE" => Area::TAR_M02AE,
            "TAR_M02AB" => Area::TAR_M02AB,
            "TAR_M02AD" => Area::TAR_M02AD,
            "TAR_M03AA" => Area::TAR_M03AA,
            "TAR_M03AD" => Area::TAR_M03AD,
            "TAR_M03AE" => Area::TAR_M03AE,
            "TAR_M03AB" => Area::TAR_M03AB,
            "TAR_M11AA" => Area::TAR_M11AA,
            "TAR_M11AB" => Area::TAR_M11AB,
            "TAR_M04AA" => Area::TAR_M04AA,
            "TAR_M05AA" => Area::TAR_M05AA,
            "TAR_M05AB" => Area::TAR_M05AB,
            "TAR_M10AA" => Area::TAR_M10AA,
            "TAR_M10AB" => Area::TAR_M10AB,
            "TAR_M10AC" => Area::TAR_M10AC,
            "TAR_M03AF" => Area::TAR_M03AF,
            "TAR_M03MG" => Area::TAR_M03MG,
            "TAR_M09AA" => Area::TAR_M09AA,
            "TAR_M09AB" => Area::TAR_M09AB,
            "TAR_M08AA" => Area::TAR_M08AA,

            "DANM13" => Area::DANM13,
            "DANM14AA" => Area::DANM14AA,
            "DANM14AB" => Area::DANM14AB,
            "DANM14AC" => Area::DANM14AC,
            "DANM14AD" => Area::DANM14AD,
            "DANM14AE" => Area::DANM14AE,
            "DANM16" => Area::DANM16,
            "DANM15" => Area::DANM15,

            "MANM26AD" => Area::MANM26AD,
            "MANM26AC" => Area::MANM26AC,
            "MANM26AA" => Area::MANM26AA,
            "MANM26AE" => Area::MANM26AE,
            "MANM26AB" => Area::MANM26AB,
            "MANM26MG" => Area::MANM26MG,
            "MANM27AA" => Area::MANM27AA,
            "MANM28AA" => Area::MANM28AA,
            "MANM28AB" => Area::MANM28AB,
            "MANM28AC" => Area::MANM28AC,
            "MANM28AD" => Area::MANM28AD,

            "KORR_M33AA" => Area::KORR_M33AA,
            "KORR_M33AB" => Area::KORR_M33AB,
            "KORR_M35AA" => Area::KORR_M35AA,
            "KORR_M36AA" => Area::KORR_M36AA,
            "KORR_M34AA" => Area::KORR_M34AA,
            "KORR_M38AA" => Area::KORR_M38AA,
            "KORR_M37AA" => Area::KORR_M37AA,
            "KORR_M38AB" => Area::KORR_M38AB,
            "KORR_M39AA" => Area::KORR_M39AA,

            "KAS_M22AA" => Area::KAS_M22AA,
            "KAS_M22AB" => Area::KAS_M22AB,
            "KAS_M23AA" => Area::KAS_M23AA,
            "KAS_M23AB" => Area::KAS_M23AB,
            "KAS_M23AC" => Area::KAS_M23AC,
            "KAS_M24AA" => Area::KAS_M24AA,
            "KAS_M25AA" => Area::KAS_M25AA,
            "KAS_M23AD" => Area::KAS_M23AD,

            "TAT_M17AB" => Area::TAT_M17AB,
            "TAT_M17AA" => Area::TAT_M17AA,
            "TAT_M17AD" => Area::TAT_M17AD,
            "TAT_M17AG" => Area::TAT_M17AG,
            "TAT_M17AE" => Area::TAT_M17AE,
            "TAT_M17MG" => Area::TAT_M17MG,
            "TAT_M17AF" => Area::TAT_M17AF,
            "TAT_M17AC" => Area::TAT_M17AC,
            "TAT_M18AA" => Area::TAT_M18AA,
            "TAT_M18AB" => Area::TAT_M18AB,
            "TAT_M20AA" => Area::TAT_M20AA,
            "TAT_M18AC" => Area::TAT_M18AC,

            "LEV_M40AA" => Area::LEV_M40AA,
            "LEV_M40AB" => Area::LEV_M40AB,
            "LEV_M40AD" => Area::LEV_M40AD,
            "LEV_M40AC" => Area::LEV_M40AC,

            "UNK_M41AA" => Area::UNK_M41AA,
            "UNK_M41AC" => Area::UNK_M41AC,
            "UNK_M43AA" => Area::UNK_M43AA,
            "UNK_M41AD" => Area::UNK_M41AD,
            "UNK_M41AB" => Area::UNK_M41AB,
            "UNK_M42AA" => Area::UNK_M42AA,
            "UNK_M44AA" => Area::UNK_M44AA,
            "UNK_M44AB" => Area::UNK_M44AB,
            "UNK_M44AC" => Area::UNK_M44AC,

            "STA_M45AA" => Area::STA_M45AA,
            "STA_M45AB" => Area::STA_M45AB,
            "STA_M45AC" => Area::STA_M45AC,
            "STA_M45AD" => Area::STA_M45AD,

            "EBO_M12AA" => Area::EBO_M12AA,
            "EBO_M41AA" => Area::EBO_M41AA,
            "EBO_M46AB" => Area::EBO_M46AB,


            "LIV_M99AA" => Area::LIV_M99AA,
            "STUNT_00" => Area::STUNT_00,
            "STUNT_03A" => Area::STUNT_03A,
            "STUNT_06" => Area::STUNT_06,
            "STUNT_07" => Area::STUNT_07,
            "M12AB" => Area::M12AB,
            "STUNT_12" => Area::STUNT_12,
            "STUNT_14" => Area::STUNT_14,
            "STUNT_16" => Area::STUNT_16,
            "STUNT_19" => Area::STUNT_19,
            "EBO_M40AA" => Area::EBO_M40AA,
            "STUNT_31B" => Area::STUNT_31B,
            "EBO_M40AD" => Area::EBO_M40AD,
            "STUNT_18" => Area::STUNT_18,
            "STUNT_35" => Area::STUNT_35,
            "STUNT_42" => Area::STUNT_42,
            "STUNT_44" => Area::STUNT_44,
            "STUNT_34" => Area::STUNT_34,
            "STUNT_50A" => Area::STUNT_50A,
            "STUNT_54A" => Area::STUNT_54A,
            "STUNT_55A" => Area::STUNT_55A,
            "STUNT_56A" => Area::STUNT_56A,
            "STUNT_57A" => Area::STUNT_57A,
            "BastilaSaved" => Area::BastilaSaved,


            other => Area::Unknown(other.to_string()),
        }
    }
}

